Bump parity-db to 0.2.4
Fix a compile error caused by a bug in parity-db crate:

```
error: failed to parse manifest at `[..]/parity-db-0.2.3/Cargo.toml`

Caused by:
  failed to parse the version requirement `0.11	` for dependency `parking_lot`

Caused by:
  expected comma after minor version number, found '\t'
```